# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc4be12412e2f5cd689161d355a51a272929241e3a37e9d422ff3a40359f4e8aaf0eaea8fa6a140291ef32856d32a382d44cd953a275c6b036d837b7cf6acbb

test:
  secret_key_base: 5826e0e6d62cdf081432a8b7f0dbf8dbdc3fd06cb85efdc441c9d4e40926d9323c6c2a0eae4f386f57f01512b75e7c82e5868d4caee137e34b035caa555b2382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
